spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/xml/db.changelog.xml
    default-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
          jwk-set-uri: https://${AUTH0_DOMAIN}/.well-known/jwks.json
gojira-api-jwt-secret: ${GOJIRA_API_JWT_SECRET}