/* tslint:disable */
/* eslint-disable */
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface SignIn200Response
 */
export interface SignIn200Response {
    /**
     * 
     * @type {string}
     * @memberof SignIn200Response
     */
    token: string;
}

/**
 * Check if a given object implements the SignIn200Response interface.
 */
export function instanceOfSignIn200Response(value: object): value is SignIn200Response {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function SignIn200ResponseFromJSON(json: any): SignIn200Response {
    return SignIn200ResponseFromJSONTyped(json, false);
}

export function SignIn200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignIn200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function SignIn200ResponseToJSON(json: any): SignIn200Response {
    return SignIn200ResponseToJSONTyped(json, false);
}

export function SignIn200ResponseToJSONTyped(value?: SignIn200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

