/* tslint:disable */
/* eslint-disable */
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * 
 * @export
 * @interface TicketResponse
 */
export interface TicketResponse {
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TicketResponse
     */
    content: string;
}

/**
 * Check if a given object implements the TicketResponse interface.
 */
export function instanceOfTicketResponse(value: object): value is TicketResponse {
    if (!('ticketId' in value) || value['ticketId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function TicketResponseFromJSON(json: any): TicketResponse {
    return TicketResponseFromJSONTyped(json, false);
}

export function TicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketId': json['ticketId'],
        'projectId': json['projectId'],
        'title': json['title'],
        'content': json['content'],
    };
}

export function TicketResponseToJSON(json: any): TicketResponse {
    return TicketResponseToJSONTyped(json, false);
}

export function TicketResponseToJSONTyped(value?: TicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticketId': value['ticketId'],
        'projectId': value['projectId'],
        'title': value['title'],
        'content': value['content'],
    };
}

