/* tslint:disable */
/* eslint-disable */
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketRequest
 */
export interface TicketRequest {
    /**
     * 
     * @type {string}
     * @memberof TicketRequest
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TicketRequest
     */
    content: string;
}

/**
 * Check if a given object implements the TicketRequest interface.
 */
export function instanceOfTicketRequest(value: object): value is TicketRequest {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function TicketRequestFromJSON(json: any): TicketRequest {
    return TicketRequestFromJSONTyped(json, false);
}

export function TicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'title': json['title'],
        'content': json['content'],
    };
}

export function TicketRequestToJSON(json: any): TicketRequest {
    return TicketRequestToJSONTyped(json, false);
}

export function TicketRequestToJSONTyped(value?: TicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'title': value['title'],
        'content': value['content'],
    };
}

